site_name: "Performance optimization analysis for your projects, as an extension to RuboCop."
repo_url: https://github.com/rubocop-hq/rubocop-performance
edit_uri: edit/master/manual/
copyright: "Copyright &copy; 2012-2019 Bozhidar Batsov and RuboCop contributors"
docs_dir: manual
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Cops: cops.md
- Cops Documentation:
    - Performance Cops: cops_performance.md
theme: readthedocs
